apiVersion: v1
kind: Service
metadata:
  name: annotation-frontend
  namespace: jamal
spec:
  type: ClusterIP
  selector:
    app: annotation-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000

