 apiVersion: v1
 kind: ConfigMap
 metadata:
   name: annotation-backend-config
   namespace: jamal
 data:
   DEBUG: "True"
   ALLOWED_HOSTS: "appbackend.forbmax.ai,annotation.forbmax.ai,192.168.18.196,192.168.18.11,192.168.18.212,localhost,127.0.0.1,192.168.18.7,192.168.18.164"
     #   CORS_ALLOWED_ORIGINS: |
     # http://annotation.forbmax.ai
     # http://appbackend.forbmax.ai
     # http://192.168.18.11:31000
     # http://192.168.18.7:31000
     # http://192.168.18.7:30152
     # http://192.168.18.7:30113
     # http://192.168.18.104:7173
     # http://192.168.18.164:8025
     # http://192.168.18.11:30080
   CORS_ALLOWED_ORIGINS: "http://appbackend.forbmax.ai,http://annotation.forbmax.ai,http://192.168.18.11:30080,http://192.168.18.11:31000,http://192.168.18.196:30081/,http://192.168.18.7:31000,http://192.168.18.7:30152,http://192.168.18.7:30113,http://192.168.18.104:7173,http://192.168.18.164:8025"
   CORS_ALLOW_CREDENTIALS: "True"
   SR_API: "http://192.168.18.164:8027/Speaker_Recognition/"
   STT_API: "http://192.168.18.81:2000/transcribe_video/"
   STATIC_URL: "static/"
   MEDIA_URL: "/media/"
   MEDIA_ROOT: "media/"


   POSTGRES_DB: annotation
   POSTGRES_USER: staging
   POSTGRES_PASSWORD: "postgrespassword"
   POSTGRES_HOST: annotation-db-rw
   POSTGRES_PORT: "5432"     
     # DATABASE_URL: "postgres://staging:postgrespassword@annotation-db-rw:5432/annotation" 
