apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: annotation-media-pvc
  namespace: jamal
spec:
  storageClassName: local-path   # <-- using hostPath dynamic provisioning
  accessModes:
    - ReadWriteOnce              # <-- RWO is required for local-path
  resources:
    requests:
      storage: 10Gi

