apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: annotation-media-pvc
  namespace: jamal
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
