apiVersion: v1
kind: Secret
metadata:
  name: annotation-backend-secret    # referenced by envFrom
  namespace: jamal
type: Opaque
stringData:
  SECRET_KEY:      "django-insecure-…"
  DEBUG:           "True"
  POSTGRES_HOST:     "annotation-db.jamal.svc.cluster.local"  # ← updated
  POSTGRES_PORT:     "5432"
  POSTGRES_DB:       "annotation"                             # ← updated
  POSTGRES_USER:     "staging"                                # ← updated
  POSTGRES_PASSWORD: "postgrespassword"                              # ← updated
  SR_API_KEY:       "apikey1"
  STT_API_KEY:      "apikey1"
  API_KEY:          "apikey2"
