apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jamal-uddin-1/Annotation.git
    targetRevision: main
    path: back-end
  destination:
    server: https://kubernetes.default.svc
    namespace: jamal                # <-- Ensure this matches the YAML manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
