apiVersion: v1
kind: Service
metadata:
  name: annotation-backend-svc
  namespace: jamal
spec:
  type: NodePort                       # <-- Changed from ClusterIP to NodePort
  selector:
    app: annotation-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080                 # <-- Ensure this is in range 30000–32767
