apiVersion: v1
kind: Service
metadata:
  name: annotation-backend-svc
  namespace: jamal
spec:
  type: ClusterIP
  selector:
    app: annotation-backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30080
